{{- $companion := .Values.companion | default dict }}
{{- $companionEnabled := dig "enabled" (.Values.services.companion.enabled | default false) $companion }}
{{- if $companionEnabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "invidious.fullname" . }}-companion
  labels:
    app: {{ template "invidious.name" . }}-companion
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    component: companion
spec:
  replicas: {{ dig "replicaCount" 1 $companion }}
  selector:
    matchLabels:
      app: {{ template "invidious.name" . }}-companion
      release: {{ .Release.Name }}
      component: companion
  template:
    metadata:
      labels:
        app: {{ template "invidious.name" . }}-companion
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        component: companion
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: companion
          image: "{{ .Values.images.companion.registry }}/{{ .Values.images.companion.image }}"
          imagePullPolicy: {{ .Values.images.companion.pullPolicy }}
          ports:
            - containerPort: 8282
          env:
            - name: SERVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.keys.companionKey }}
          {{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          {{- end }}
          {{- if get $companion "resources" }}
          resources:
{{ toYaml (get $companion "resources") | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: companion-cache
              mountPath: /var/tmp/youtubei.js
          {{- if get $companion "livenessProbe" }}
          livenessProbe:
{{ toYaml (get $companion "livenessProbe") | indent 12 }}
          {{- end }}
          {{- if get $companion "readinessProbe" }}
          readinessProbe:
{{ toYaml (get $companion "readinessProbe") | indent 12 }}
          {{- end }}
      volumes:
        - name: companion-cache
          emptyDir: {}
      restartPolicy: Always
{{- end }}
