---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    app: {{ template "invidious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "invidious.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "invidious.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: {{ .Values.podSecurityContext.runAsUser }}
        runAsGroup: {{ .Values.podSecurityContext.runAsGroup }}
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
        runAsNonRoot: {{ .Values.podSecurityContext.runAsNonRoot }}
        seccompProfile:
          type: {{ .Values.podSecurityContext.seccompProfile.type }}
      initContainers:
        - name: wait-for-postgresql
          image: postgres:14
          args:
            - /bin/sh
            - -c
            - until pg_isready -h {{ .Values.config.db.host }} -p {{ .Values.config.db.port }} -U {{ .Values.config.db.user }}; do echo waiting for database; sleep 2; done;
      containers:
        - name: invidious
          image: "{{ .Values.images.invidious.registry }}/{{ .Values.images.invidious.image }}"
          imagePullPolicy: {{ .Values.images.invidious.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: INVIDIOUS_CONFIG
              valueFrom:
                configMapKeyRef:
                  key: INVIDIOUS_CONFIG
                  name: {{ template "invidious.fullname" . }}
          securityContext:
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: {{ .Values.securityContext.seccompProfile.type }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/v1/trending
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 3000
              path: /api/v1/trending
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 2
        - name: companion
          image: "{{ .Values.images.companion.registry }}/{{ .Values.images.companion.image }}"
          imagePullPolicy: {{ .Values.images.companion.pullPolicy }}
          ports:
            - containerPort: 8282
          env:
            - name: SERVER_SECRET_KEY
              value: "{{ .Values.config.invidious_companion_key }}"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: companion-cache
              mountPath: /var/tmp/youtubei.js
          livenessProbe:
            httpGet:
              port: 8282
              path: /
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              port: 8282
              path: /
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: companion-cache
          emptyDir: {}
      restartPolicy: Always
