---
{{- $dbImage := .Values.database.image | default .Values.database.internal.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "invidious.fullname" . }}
  labels:
    app: {{ template "invidious.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "invidious.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "invidious.config" . | sha256sum }}
      labels:
        app: {{ template "invidious.name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-database
          image: "{{ $dbImage.registry }}/{{ $dbImage.repository }}:{{ $dbImage.tag }}"
          imagePullPolicy: {{ $dbImage.pullPolicy | default "IfNotPresent" }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.keys.databaseUsername }}
          args:
            - /bin/sh
            - -c
            - |
              {{- if .Values.database.internal.enabled }}
              until pg_isready -h {{ template "invidious.fullname" . }}-postgresql -p 5432 -U "$POSTGRES_USER"; do
              {{- else }}
              until pg_isready -h {{ .Values.database.external.host }} -p {{ .Values.database.external.port }} -U "$POSTGRES_USER"; do
              {{- end }}
                echo "Waiting for database..."; sleep 2;
              done;
        - name: migrate-database
          image: "{{ .Values.images.invidious.registry }}/{{ .Values.images.invidious.image }}"
          imagePullPolicy: {{ .Values.images.invidious.pullPolicy }}
          command:
            - /sbin/tini
            - --
          args:
            - /invidious/invidious
            - --migrate
          env:
{{ include "invidious.env" . | indent 12 }}
      containers:
        - name: invidious
          image: "{{ .Values.images.invidious.registry }}/{{ .Values.images.invidious.image }}"
          imagePullPolicy: {{ .Values.images.invidious.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
{{ include "invidious.env" . | indent 12 }}
          {{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              port: 3000
              path: /
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
      restartPolicy: Always
