{{- if .Values.materialious.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "invidious.fullname" . }}-materialious
  labels:
    app: {{ template "invidious.name" . }}-materialious
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    component: materialious
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "invidious.name" . }}-materialious
      release: {{ .Release.Name }}
      component: materialious
  template:
    metadata:
      labels:
        app: {{ template "invidious.name" . }}-materialious
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        component: materialious
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- end }}
      containers:
        - name: materialious
          image: "{{ .Values.images.materialious.registry }}/{{ .Values.images.materialious.repository }}:{{ .Values.images.materialious.tag }}{{ with .Values.images.materialious.digest }}@{{ . }}{{ end }}"
          imagePullPolicy: {{ .Values.images.materialious.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: VITE_DEFAULT_INVIDIOUS_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_INVIDIOUS_INSTANCE | default (printf "http://%s-invidious:3000" (include "invidious.fullname" .)) }}
            - name: VITE_DEFAULT_COMPANION_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_COMPANION_INSTANCE | default (printf "http://%s-companion:8282" (include "invidious.fullname" .)) }}
            - name: VITE_DEFAULT_RETURNYTDISLIKES_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_RETURNYTDISLIKES_INSTANCE }}
            - name: VITE_DEFAULT_SPONSERBLOCK_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_SPONSERBLOCK_INSTANCE }}
            - name: VITE_DEFAULT_DEARROW_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_DEARROW_INSTANCE }}
            - name: VITE_DEFAULT_DEARROW_THUMBNAIL_INSTANCE
              value: {{ .Values.materialious.config.VITE_DEFAULT_DEARROW_THUMBNAIL_INSTANCE }}
            - name: VITE_DEFAULT_SETTINGS
              value: {{ .Values.materialious.config.VITE_DEFAULT_SETTINGS | quote }}
          {{- if .Values.securityContext }}
          securityContext:
{{ toYaml .Values.securityContext | indent 12 }}
          {{- end }}
          {{- if .Values.materialious.resources }}
          resources:
{{ toYaml .Values.materialious.resources | indent 12 }}
          {{- end }}
          {{- if .Values.materialious.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.materialious.readinessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.materialious.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.materialious.livenessProbe | indent 12 }}
          {{- end }}
      restartPolicy: Always
{{- end }}
