{{- range $svcName, $svcValues := .Values.services }}
{{- if $svcValues.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "invidious.fullname" $) $svcName }}
  labels:
    app: {{ include "invidious.name" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    service: {{ $svcName }}
spec:
  type: {{ $svcValues.type }}
  ports:
    - name: http
      port: {{ $svcValues.port }}
      targetPort: {{ $svcValues.port }}
  selector:
    {{- if eq $svcName "materialious" }}
    app: {{ include "invidious.name" $ }}-materialious
    component: materialious
    {{- else }}
    app: {{ include "invidious.name" $ }}
    {{- end }}
    release: {{ $.Release.Name }}
{{- if $svcValues.loadBalancerIP }}
  loadBalancerIP: {{ $svcValues.loadBalancerIP }}
{{- end }}
{{- end }}
{{- end }}
