{{- range $svcName, $svcConfig := .Values.services }}
{{- if $svcConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "invidious.fullname" $ }}-{{ $svcName }}
  labels:
    app: {{ include "invidious.name" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
    service: {{ $svcName }}
spec:
  type: {{ $svcConfig.type }}
  ports:
    - name: http
      port: {{ $svcConfig.port }}
      targetPort: {{ $svcConfig.port }}
  selector:
    {{- if ne $svcName "invidious" }}
    app: {{ include "invidious.name" $ }}-{{ $svcName }}
    component: {{ $svcName }}
    {{- else }}
    app: {{ include "invidious.name" $ }}
    {{- end }}
    release: {{ $.Release.Name }}
  {{- if $svcConfig.loadBalancerIP }}
  loadBalancerIP: {{ $svcConfig.loadBalancerIP }}
  {{- end }}
{{- end }}
{{- end }}
